title: BPAI — Brightpath Technology & Services Pvt. Ltd.
description: Cutting-edge, production-ready AI. Privacy-first. Currently in stealth.
url: https://bpai.in
logo: /assets/img/FullLogo_Transparent.png
favicon: /assets/img/favicon.ico

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional but good for rich previews
# twitter:
#   username: your_twitter_handle
# social:
#   name: Brightpath Technology & Services Pvt. Ltd.
#   links:
#     - https://www.linkedin.com/company/your-company
#     - https://github.com/rmsai25
