title: BPAI — Brightpath Technology & Services Pvt. Ltd.
description: Cutting-edge, production-ready AI. Privacy-first. Currently in stealth.
url: https://bpai.in
logo: /assets/img/FullLogo_Transparent.png
favicon: /assets/img/favicon.ico

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

email: team@bpai.in
